name: Build Speedhack Dylib

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Dylib
        run: |
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          clang -dynamiclib \
            -isysroot "$SDK_PATH" \
            -arch arm64 \
            -miphoneos-version-min=14.0 \
            -framework Foundation \
            -fobjc-arc \
            -O3 \
            speedhack.m fishhook.c \
            -o speedhack.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: speedhack-dylib
          path: speedhack.dylib
